INFO 2024-02-21 13:00:42,765 autoreload 2620 12896 Watching for file changes with StatReloader
WARNING 2024-02-21 13:01:26,852 log 2620 9916 Unauthorized: /assets/api/asset/
WARNING 2024-02-21 13:01:26,853 basehttp 2620 9916 "GET /assets/api/asset/ HTTP/1.1" 401 58
WARNING 2024-02-21 13:01:57,697 log 2620 9916 Method Not Allowed: /auth/sign-up/
WARNING 2024-02-21 13:01:57,698 basehttp 2620 9916 "GET /auth/sign-up/ HTTP/1.1" 405 40
ERROR 2024-02-21 13:02:04,405 log 2620 9916 Internal Server Error: /auth/sign-up/
Traceback (most recent call last):
  File "D:\0_Pycharm\eAssets\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\0_Pycharm\eAssets\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\0_Pycharm\eAssets\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\0_Pycharm\eAssets\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\0_Pycharm\eAssets\venv\Lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\0_Pycharm\eAssets\venv\Lib\site-packages\rest_framework\views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
ERROR 2024-02-21 13:02:04,408 basehttp 2620 9916 "POST /auth/sign-up/ HTTP/1.1" 500 84469
ERROR 2024-02-21 13:03:11,928 log 2620 9916 Internal Server Error: /auth/sign-up/
Traceback (most recent call last):
  File "D:\0_Pycharm\eAssets\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\0_Pycharm\eAssets\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\0_Pycharm\eAssets\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\0_Pycharm\eAssets\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\0_Pycharm\eAssets\venv\Lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\0_Pycharm\eAssets\venv\Lib\site-packages\rest_framework\views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
ERROR 2024-02-21 13:03:11,930 basehttp 2620 9916 "POST /auth/sign-up/ HTTP/1.1" 500 84469
ERROR 2024-02-21 13:04:27,589 log 2620 9916 Internal Server Error: /auth/sign-up/
Traceback (most recent call last):
  File "D:\0_Pycharm\eAssets\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\0_Pycharm\eAssets\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\0_Pycharm\eAssets\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\0_Pycharm\eAssets\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\0_Pycharm\eAssets\venv\Lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\0_Pycharm\eAssets\venv\Lib\site-packages\rest_framework\views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
ERROR 2024-02-21 13:04:27,591 basehttp 2620 9916 "POST /auth/sign-up/ HTTP/1.1" 500 84469
ERROR 2024-02-21 13:05:02,080 log 2620 9916 Internal Server Error: /auth/sign-up/
Traceback (most recent call last):
  File "D:\0_Pycharm\eAssets\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\0_Pycharm\eAssets\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\0_Pycharm\eAssets\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\0_Pycharm\eAssets\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\0_Pycharm\eAssets\venv\Lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\0_Pycharm\eAssets\venv\Lib\site-packages\rest_framework\views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
ERROR 2024-02-21 13:05:02,082 basehttp 2620 9916 "POST /auth/sign-up/ HTTP/1.1" 500 84469
INFO 2024-02-21 13:05:40,699 autoreload 15644 13900 Watching for file changes with StatReloader
ERROR 2024-02-21 13:05:45,020 log 15644 1488 Internal Server Error: /auth/sign-up/
Traceback (most recent call last):
  File "D:\0_Pycharm\eAssets\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\0_Pycharm\eAssets\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\0_Pycharm\eAssets\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\0_Pycharm\eAssets\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\0_Pycharm\eAssets\venv\Lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\0_Pycharm\eAssets\venv\Lib\site-packages\rest_framework\views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
ERROR 2024-02-21 13:05:45,023 basehttp 15644 1488 "POST /auth/sign-up/ HTTP/1.1" 500 84469
INFO 2024-02-21 13:06:31,571 basehttp 15644 1488 "POST /auth/sign-up/ HTTP/1.1" 200 71
WARNING 2024-02-21 13:08:14,682 log 15644 1488 Bad Request: /auth/sign-in/
WARNING 2024-02-21 13:08:14,682 basehttp 15644 1488 "POST /auth/sign-in/ HTTP/1.1" 400 108
INFO 2024-02-21 13:08:29,266 basehttp 15644 1488 "POST /auth/sign-in/ HTTP/1.1" 200 483
INFO 2024-02-21 13:11:12,659 basehttp 15644 1488 "GET /assets/api/asset/ HTTP/1.1" 200 73655
INFO 2024-02-21 13:12:12,420 autoreload 15644 13900 D:\0_Pycharm\eAssets\assets\api\views.py changed, reloading.
INFO 2024-02-21 13:12:13,300 autoreload 10748 17696 Watching for file changes with StatReloader
INFO 2024-02-21 13:12:16,674 basehttp 10748 3328 "GET /assets/api/asset/ HTTP/1.1" 200 73655
INFO 2024-02-21 13:12:23,195 basehttp 10748 3328 "GET /assets/api/asset/ HTTP/1.1" 200 73655
INFO 2024-02-21 13:12:39,375 autoreload 10748 17696 D:\0_Pycharm\eAssets\assets\api\views.py changed, reloading.
INFO 2024-02-21 13:12:40,282 autoreload 14512 14892 Watching for file changes with StatReloader
INFO 2024-02-21 13:13:45,890 autoreload 14512 14892 D:\0_Pycharm\eAssets\assets\api\views.py changed, reloading.
INFO 2024-02-21 13:13:46,752 autoreload 16160 4448 Watching for file changes with StatReloader
WARNING 2024-02-21 13:13:51,450 log 16160 17684 Unauthorized: /assets/api/asset/
WARNING 2024-02-21 13:13:51,451 basehttp 16160 17684 "GET /assets/api/asset/ HTTP/1.1" 401 183
INFO 2024-02-21 13:14:39,021 basehttp 16160 17684 "GET /auth/sign-in HTTP/1.1" 301 0
WARNING 2024-02-21 13:14:39,031 log 16160 12672 Method Not Allowed: /auth/sign-in/
WARNING 2024-02-21 13:14:39,032 basehttp 16160 12672 "GET /auth/sign-in/ HTTP/1.1" 405 40
ERROR 2024-02-21 13:14:45,070 log 16160 12672 Internal Server Error: /auth/sign-in
Traceback (most recent call last):
  File "D:\0_Pycharm\eAssets\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\0_Pycharm\eAssets\venv\Lib\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\0_Pycharm\eAssets\venv\Lib\site-packages\django\middleware\common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\0_Pycharm\eAssets\venv\Lib\site-packages\django\middleware\common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to localhost:8000/auth/sign-in/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
ERROR 2024-02-21 13:14:45,071 basehttp 16160 12672 "POST /auth/sign-in HTTP/1.1" 500 75106
ERROR 2024-02-21 13:15:05,939 log 16160 7240 Internal Server Error: /auth/sign-in
Traceback (most recent call last):
  File "D:\0_Pycharm\eAssets\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\0_Pycharm\eAssets\venv\Lib\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\0_Pycharm\eAssets\venv\Lib\site-packages\django\middleware\common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\0_Pycharm\eAssets\venv\Lib\site-packages\django\middleware\common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to localhost:8000/auth/sign-in/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
ERROR 2024-02-21 13:15:05,941 basehttp 16160 7240 "POST /auth/sign-in HTTP/1.1" 500 75106
INFO 2024-02-21 13:15:15,276 autoreload 12060 15876 Watching for file changes with StatReloader
ERROR 2024-02-21 13:15:33,131 log 12060 2928 Internal Server Error: /auth/sign-in
Traceback (most recent call last):
  File "D:\0_Pycharm\eAssets\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\0_Pycharm\eAssets\venv\Lib\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\0_Pycharm\eAssets\venv\Lib\site-packages\django\middleware\common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\0_Pycharm\eAssets\venv\Lib\site-packages\django\middleware\common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to localhost:8000/auth/sign-in/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
ERROR 2024-02-21 13:15:33,134 basehttp 12060 2928 "POST /auth/sign-in HTTP/1.1" 500 75106
INFO 2024-02-21 13:16:12,209 basehttp 12060 8936 "POST /auth/sign-in/ HTTP/1.1" 200 483
INFO 2024-02-21 13:16:43,621 basehttp 12060 8936 "GET /assets/api/asset/ HTTP/1.1" 200 73655
INFO 2024-02-21 13:17:01,559 basehttp 12060 8936 "GET /assets/api/asset/ HTTP/1.1" 200 73655
INFO 2024-02-21 13:17:06,021 basehttp 12060 8936 "GET /assets/api/asset/ HTTP/1.1" 200 73655
INFO 2024-02-21 13:18:17,403 autoreload 12060 15876 D:\0_Pycharm\eAssets\assets\api\views.py changed, reloading.
INFO 2024-02-21 13:18:18,269 autoreload 2096 7312 Watching for file changes with StatReloader
INFO 2024-02-21 13:18:29,929 autoreload 2096 7312 D:\0_Pycharm\eAssets\assets\api\views.py changed, reloading.
INFO 2024-02-21 13:18:30,787 autoreload 10088 14896 Watching for file changes with StatReloader
INFO 2024-02-21 13:19:59,448 autoreload 10088 14896 D:\0_Pycharm\eAssets\assets\api\views.py changed, reloading.
INFO 2024-02-21 13:20:00,351 autoreload 16480 10504 Watching for file changes with StatReloader
INFO 2024-02-21 13:20:04,148 basehttp 16480 7632 "GET /assets/api/asset/ HTTP/1.1" 200 73655
INFO 2024-02-21 13:20:52,571 basehttp 16480 7632 "GET /assets/api/asset/122/ HTTP/1.1" 200 348
WARNING 2024-02-21 13:21:24,174 log 16480 7632 Unauthorized: /assets/api/department/
WARNING 2024-02-21 13:21:24,175 basehttp 16480 7632 "GET /assets/api/department/ HTTP/1.1" 401 183
WARNING 2024-02-21 13:22:11,679 log 16480 7632 Unauthorized: /assets/api/department/
WARNING 2024-02-21 13:22:11,680 basehttp 16480 7632 "GET /assets/api/department/ HTTP/1.1" 401 183
INFO 2024-02-21 13:23:25,201 autoreload 16480 10504 D:\0_Pycharm\eAssets\assets\api\views.py changed, reloading.
INFO 2024-02-21 13:23:26,161 autoreload 13920 12920 Watching for file changes with StatReloader
INFO 2024-02-21 13:23:29,447 autoreload 13920 12920 D:\0_Pycharm\eAssets\assets\api\views.py changed, reloading.
INFO 2024-02-21 13:23:30,306 autoreload 18048 11236 Watching for file changes with StatReloader
WARNING 2024-02-21 13:23:49,177 log 18048 9596 Unauthorized: /assets/api/department/
WARNING 2024-02-21 13:23:49,178 basehttp 18048 9596 "GET /assets/api/department/ HTTP/1.1" 401 183
INFO 2024-02-21 13:24:48,809 basehttp 18048 9596 "POST /auth/sign-in/ HTTP/1.1" 200 483
INFO 2024-02-21 13:25:51,945 basehttp 18048 9596 "GET /assets/api/department/ HTTP/1.1" 200 485
INFO 2024-02-21 13:26:05,225 basehttp 18048 9596 "GET /assets/api/department/ HTTP/1.1" 200 485
INFO 2024-02-21 13:26:06,578 basehttp 18048 9596 "GET /assets/api/department/ HTTP/1.1" 200 485
INFO 2024-02-21 13:26:18,037 autoreload 18048 11236 D:\0_Pycharm\eAssets\assets\api\views.py changed, reloading.
INFO 2024-02-21 13:26:18,913 autoreload 17736 15264 Watching for file changes with StatReloader
INFO 2024-02-21 13:26:34,409 autoreload 17736 15264 D:\0_Pycharm\eAssets\assets\api\views.py changed, reloading.
INFO 2024-02-21 13:26:35,279 autoreload 8456 15308 Watching for file changes with StatReloader
INFO 2024-02-21 13:26:40,165 basehttp 8456 1396 "GET /assets/api/department/ HTTP/1.1" 200 485
INFO 2024-02-21 13:44:25,904 autoreload 8456 15308 D:\0_Pycharm\eAssets\assets\api\views.py changed, reloading.
INFO 2024-02-21 13:44:26,867 autoreload 5396 8212 Watching for file changes with StatReloader
INFO 2024-02-21 13:45:43,014 autoreload 5396 8212 D:\0_Pycharm\eAssets\assets\api\views.py changed, reloading.
INFO 2024-02-21 13:45:43,910 autoreload 19184 4448 Watching for file changes with StatReloader
INFO 2024-02-23 12:21:21,175 autoreload 11804 12132 Watching for file changes with StatReloader
WARNING 2024-02-23 12:21:25,799 log 11804 1672 Unauthorized: /assets/api/department/
WARNING 2024-02-23 12:21:25,800 basehttp 11804 1672 "GET /assets/api/department/ HTTP/1.1" 401 183
INFO 2024-02-23 12:23:15,648 autoreload 11804 12132 D:\0_Pycharm\eAssets\eAssets\settings.py changed, reloading.
INFO 2024-02-23 12:23:16,558 autoreload 12392 4808 Watching for file changes with StatReloader
WARNING 2024-02-23 12:23:22,335 log 12392 8292 Unauthorized: /assets/api/department/
WARNING 2024-02-23 12:23:22,336 basehttp 12392 8292 "GET /assets/api/department/ HTTP/1.1" 401 183
WARNING 2024-02-23 12:23:36,403 log 12392 8292 Unauthorized: /assets/api/department/
WARNING 2024-02-23 12:23:36,404 basehttp 12392 8292 "GET /assets/api/department/ HTTP/1.1" 401 183
WARNING 2024-02-23 12:24:07,991 log 12392 8292 Unauthorized: /auth/sign-in/
WARNING 2024-02-23 12:24:07,992 basehttp 12392 8292 "POST /auth/sign-in/ HTTP/1.1" 401 63
INFO 2024-02-23 12:24:36,084 basehttp 12392 8292 "POST /auth/sign-in/ HTTP/1.1" 200 483
WARNING 2024-02-23 12:25:19,234 log 12392 8292 Unauthorized: /assets/api/department/
WARNING 2024-02-23 12:25:19,235 basehttp 12392 8292 "GET /assets/api/department/ HTTP/1.1" 401 183
INFO 2024-02-23 12:25:40,273 basehttp 12392 8292 "GET /assets/api/department/ HTTP/1.1" 200 629
INFO 2024-02-23 12:26:28,238 basehttp 12392 8292 "POST /assets/api/department/ HTTP/1.1" 201 143
INFO 2024-02-23 12:26:34,531 basehttp 12392 8292 "GET /assets/api/department/ HTTP/1.1" 200 773
INFO 2024-02-23 12:28:46,197 autoreload 12392 4808 D:\0_Pycharm\eAssets\assets\models.py changed, reloading.
INFO 2024-02-23 12:28:47,071 autoreload 12548 15044 Watching for file changes with StatReloader
INFO 2024-02-23 12:29:15,216 autoreload 12548 15044 D:\0_Pycharm\eAssets\assets\models.py changed, reloading.
INFO 2024-02-23 12:29:16,311 autoreload 12736 9704 Watching for file changes with StatReloader
INFO 2024-02-23 12:31:01,990 autoreload 12736 9704 D:\0_Pycharm\eAssets\assets\api\views.py changed, reloading.
INFO 2024-02-23 12:31:02,848 autoreload 2080 2960 Watching for file changes with StatReloader
INFO 2024-02-23 12:33:14,137 autoreload 2080 2960 D:\0_Pycharm\eAssets\assets\api\views.py changed, reloading.
INFO 2024-02-23 12:33:15,068 autoreload 17392 8696 Watching for file changes with StatReloader
INFO 2024-02-23 12:39:05,119 autoreload 17392 8696 D:\0_Pycharm\eAssets\assets\api\views.py changed, reloading.
INFO 2024-02-23 12:39:06,016 autoreload 16220 4180 Watching for file changes with StatReloader
INFO 2024-02-23 12:40:28,960 autoreload 16220 4180 D:\0_Pycharm\eAssets\assets\api\views.py changed, reloading.
INFO 2024-02-23 12:40:29,880 autoreload 16336 11328 Watching for file changes with StatReloader
INFO 2024-02-23 12:45:06,958 autoreload 16336 11328 D:\0_Pycharm\eAssets\assets\api\views.py changed, reloading.
INFO 2024-02-23 12:45:07,821 autoreload 8196 16556 Watching for file changes with StatReloader
INFO 2024-02-23 12:45:15,467 autoreload 8196 16556 D:\0_Pycharm\eAssets\assets\api\views.py changed, reloading.
INFO 2024-02-23 12:45:16,415 autoreload 12728 8128 Watching for file changes with StatReloader
INFO 2024-02-23 12:46:16,908 autoreload 12728 8128 D:\0_Pycharm\eAssets\assets\api\views.py changed, reloading.
INFO 2024-02-23 12:46:17,833 autoreload 17900 11900 Watching for file changes with StatReloader
INFO 2024-02-23 12:53:04,892 autoreload 17900 11900 D:\0_Pycharm\eAssets\assets\api\views.py changed, reloading.
INFO 2024-02-23 12:53:05,823 autoreload 19452 15620 Watching for file changes with StatReloader
INFO 2024-02-23 12:53:42,867 basehttp 19452 6016 "GET /assets/api/department/ HTTP/1.1" 200 773
ERROR 2024-02-23 12:53:59,999 views 19452 6016 An error occurred while processing the POST request when creating the Department...
Traceback (most recent call last):
  File "D:\0_Pycharm\eAssets\assets\api\views.py", line 86, in post
    action_description = f"Created a department: {department.name} ({department.id})"
                                                  ^^^^^^^^^^^^^^^
AttributeError: 'Department' object has no attribute 'name'
ERROR 2024-02-23 12:54:00,001 log 19452 6016 Internal Server Error: /assets/api/department/
ERROR 2024-02-23 12:54:00,002 basehttp 19452 6016 "POST /assets/api/department/ HTTP/1.1" 500 33
INFO 2024-02-23 12:55:23,560 autoreload 19452 15620 D:\0_Pycharm\eAssets\assets\api\views.py changed, reloading.
INFO 2024-02-23 12:55:24,600 autoreload 10572 10100 Watching for file changes with StatReloader
ERROR 2024-02-23 12:55:30,781 views 10572 15356 An error occurred while processing the POST request when creating the Department...
Traceback (most recent call last):
  File "D:\0_Pycharm\eAssets\assets\api\views.py", line 86, in post
    action_description = f"Created a department: {department.name} ({department.id})"
                                                  ^^^^^^^^^^^^^^^
AttributeError: 'Department' object has no attribute 'name'
ERROR 2024-02-23 12:55:30,783 log 10572 15356 Internal Server Error: /assets/api/department/
ERROR 2024-02-23 12:55:30,784 basehttp 10572 15356 "POST /assets/api/department/ HTTP/1.1" 500 33
INFO 2024-02-23 12:56:24,306 autoreload 10572 10100 D:\0_Pycharm\eAssets\assets\api\views.py changed, reloading.
INFO 2024-02-23 12:56:25,586 autoreload 4452 13136 Watching for file changes with StatReloader
INFO 2024-02-23 12:56:35,128 autoreload 11172 10740 Watching for file changes with StatReloader
INFO 2024-02-23 12:56:41,869 basehttp 11172 14296 "GET /assets/api/department/ HTTP/1.1" 200 1061
ERROR 2024-02-23 12:56:57,859 views 11172 14296 An error occurred while processing the POST request when creating the Department...
Traceback (most recent call last):
  File "D:\0_Pycharm\eAssets\assets\api\views.py", line 86, in post
    action_description = f"Created a department: {department.name} ({department.id})"
                                                  ^^^^^^^^^^^^^^^
AttributeError: 'Department' object has no attribute 'name'
ERROR 2024-02-23 12:56:57,860 log 11172 14296 Internal Server Error: /assets/api/department/
ERROR 2024-02-23 12:56:57,861 basehttp 11172 14296 "POST /assets/api/department/ HTTP/1.1" 500 33
INFO 2024-02-23 12:57:02,996 basehttp 11172 14296 "GET /assets/api/department/ HTTP/1.1" 200 1205
ERROR 2024-02-23 12:57:10,029 views 11172 14296 An error occurred while processing the POST request when creating the Department...
Traceback (most recent call last):
  File "D:\0_Pycharm\eAssets\assets\api\views.py", line 86, in post
    action_description = f"Created a department: {department.name} ({department.id})"
                                                  ^^^^^^^^^^^^^^^
AttributeError: 'Department' object has no attribute 'name'
ERROR 2024-02-23 12:57:10,030 log 11172 14296 Internal Server Error: /assets/api/department/
ERROR 2024-02-23 12:57:10,031 basehttp 11172 14296 "POST /assets/api/department/ HTTP/1.1" 500 33
INFO 2024-02-23 12:59:33,644 autoreload 11172 10740 D:\0_Pycharm\eAssets\assets\api\views.py changed, reloading.
INFO 2024-02-23 12:59:34,518 autoreload 15380 15612 Watching for file changes with StatReloader
ERROR 2024-02-23 12:59:39,329 views 15380 8412 An error occurred while processing the POST request when creating the Department...
Traceback (most recent call last):
  File "D:\0_Pycharm\eAssets\assets\api\views.py", line 87, in post
    UserAction.objects.create(user=request.user, action=action_description, timestamp=timezone.now())
                                                                                      ^^^^^^^^^^^^
AttributeError: type object 'datetime.timezone' has no attribute 'now'
ERROR 2024-02-23 12:59:39,330 log 15380 8412 Internal Server Error: /assets/api/department/
ERROR 2024-02-23 12:59:39,331 basehttp 15380 8412 "POST /assets/api/department/ HTTP/1.1" 500 33
INFO 2024-02-23 13:00:32,045 autoreload 15380 15612 D:\0_Pycharm\eAssets\assets\api\views.py changed, reloading.
INFO 2024-02-23 13:00:32,925 autoreload 16288 6324 Watching for file changes with StatReloader
INFO 2024-02-23 13:00:37,370 basehttp 16288 11924 "POST /assets/api/department/ HTTP/1.1" 201 144
INFO 2024-02-23 13:00:47,476 basehttp 16288 11924 "GET /assets/api/department/ HTTP/1.1" 200 1639
INFO 2024-02-23 13:01:39,842 autoreload 16288 6324 D:\0_Pycharm\eAssets\assets\api\views.py changed, reloading.
INFO 2024-02-23 13:01:40,725 autoreload 10196 18456 Watching for file changes with StatReloader
INFO 2024-02-23 13:02:37,308 basehttp 10196 8836 "GET /assets/api/department/ HTTP/1.1" 200 1639
INFO 2024-02-23 13:02:47,395 basehttp 10196 8836 "POST /assets/api/department/ HTTP/1.1" 201 144
